# Generated by Django 4.2.3 on 2023-07-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='read',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
